Revert "media: v4l2-ioctl: Use larger on-stack video copy buffers"
error: use of undeclared identifier 'array_buf'

This reverts commit 23e0100873fa91c8c1690105da902626c0cb7d8c.

Signed-off-by: Salman Wahib <sxlmnwb.dev@gmail.com>